modLoader = "javafml"
loaderVersion = "[41,)"
license = "MIT"

[[mods]]
modId = "dropz"
version = "${version}"
displayName = "Dropz"
authors = "Lazurite Team"
description = "Item physics in Minecraft."
logoFile = "icon.png"

[[dependencies.dropz]]
modId = "forge"
mandatory = true
versionRange = "[41,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.dropz]]
modId = "minecraft"
mandatory = true
versionRange = "[1.19,)"
ordering = "NONE"
side = "BOTH"